baseURL = "/"
languageCode = "en-us"
title = "Front end life"
theme = "coder"
paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[permalinks]
    posts = "posts/:title/"
    default = ":title/"

[params]
    author = "Sambath Kumar Logakrishnan"
    description = "professional website"
    keywords = "blog,developer,personal"
    info = "Full Stack Dev & lambda calculus"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/sambathl"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/samkumar15"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/sambathl/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
